version: "3.9"

services:
  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    restart: unless-stopped
    networks:
      - keycloak-network
    environment:
      PGRST_DB_URI: postgres://appuser:appdb_pass@postgres-other:5432/appdb
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: appuser
      PGRST_JWT_SECRET: your_jwt_secret_here
    depends_on:
      postgres-other:
        condition: service_healthy
