version: "3.9"

services:
  postgres-keycloak:
    image: postgres:16
    container_name: postgres-keycloak
    restart: unless-stopped
    networks:
      - keycloak-network
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_db_pass
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      retries: 5

  postgres-other:
    image: postgres:16
    container_name: postgres-other
    restart: unless-stopped
    networks:
      - keycloak-network
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appdb_pass
    volumes:
      - postgres-app-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 10s
      retries: 5
