
services:
  external_management:
    image: postgrest/postgrest:latest
    container_name: external_management
    environment:
      - PGRST_DB_URI=${POSTGREST_DB_URI}
      - PGRST_DB_ANON_ROLE=${POSTGREST_ANON_ROLE}
      - PGRST_JWT_SECRET=${POSTGREST_JWT_SECRET}
    ports:
      - "${POSTGREST_PORT}:3000"
    depends_on:
      external_postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
