services:
  external_management:
    image: postgrest/postgrest:latest
    container_name: external_management
    environment:
      - PGRST_DB_URI=${POSTGREST_DB_URI}
      - PGRST_DB_ANON_ROLE=${POSTGREST_ANON_ROLE}
      - PGRST_JWT_SECRET=${POSTGREST_JWT_SECRET}
    ports:
      - "${POSTGREST_PORT}:3000"
    depends_on:
      - external_postgres
    restart: unless-stopped
